name: advance_flutter_ch1
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  blurrycontainer: ^2.1.0
  google_fonts: ^6.2.1
#  image_gallery_saver: ^2.0.3
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
